# Config file for all scripts

# hardening_checks.py
lynis:
   repo:               https://github.com/CISOfy/lynis
   lynis_file:         lynis.sh
   local_report:       /var/log/lynis/lynis-report.dat
   report_path:        /opt/jenkins-slave/workspace/lynis_reports/
   report_file_name:   lynis_result.txt
john:
   shadow: /etc/shadow
   passwd: /etc/passwd
hostnames:
   hostnames_path: /etc/openstack_deploy/openstack_hostnames_ips.yml