# Config file for all scripts

# hardening_checks.py
lynis:
   repo:       https://github.com/CISOfy/lynis
   lynis_file: lynis.sh
john:
   shadow: /etc/shadow
   passwd: /etc/passwd
hostnames:
   hostnames_path: /etc/openstack_deploy/openstack_hostnames_ips.yml